# Puerto
quarkus.http.port=8080

# ms-risk
quarkus.rest-client.risk-api.url=http://localhost:8081

# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=1234
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/creditdb

quarkus.hibernate-orm.database.generation=update